### ISSUE TITLE
separate out individual objects

### ISSUE THREAD

**Issue by mjmartin23** [mjmartin23/ivr-vision#7]
kmeans gives a perfect separation from the output of `median_filter`:
![kmeans_extract](https://cloud.githubusercontent.com/assets/8230455/19388739/106c4e1a-9219-11e6-9697-ad576260bb28.png)

However, we have an unknown number of clusters so we can't use kmeans unless we find a way to identify the number of clusters in the image.

I'm trying hierarchical clustering since that doesn't requite a pre-determined number of clusters.

Also things to look into: Matlab functions `bwboundaries` (looks promising) and `regionprops`.

**Comment by mjmartin23** [comment]
median filter to boundary:
![selection_005](https://cloud.githubusercontent.com/assets/8230455/19392274/03005d66-9228-11e6-9738-53bb2ab4edbc.png)

**Comment by Dylan3636** [comment]
Managed to separate them using the output of boundary and extract.
